name: Pre-build checks

on:
  push:
    branches: [ nsk-timezone ]
  pull_request:
    branches: [ nsk-timezone ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "Success"
